# Generated by Django 5.2.1 on 2025-06-04 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routes', '0002_initial'),
        ('shipments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historialestado',
            name='actualizador',
            field=models.ForeignKey(blank=True, help_text='Usuario que cambió el estado', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historialestado',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='routes.estado'),
        ),
        migrations.AddField(
            model_name='paquete',
            name='cliente_destinatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios_recibidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paquete',
            name='cliente_remitente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios_realizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paquete',
            name='estado_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='routes.estado'),
        ),
        migrations.AddField(
            model_name='paquete',
            name='ruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='routes.ruta'),
        ),
        migrations.AddField(
            model_name='historialestado',
            name='paquete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiales', to='shipments.paquete'),
        ),
    ]
