# Generated by Django 5.2.1 on 2025-06-11 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=255)),
                ('destinos', models.TextField()),
                ('distancia_total', models.FloatField()),
                ('duracion_total', models.FloatField()),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
